import { NextResponse } from "next/server";

const instructors = [
  {
    id: 1,
    name: "أحمد توفيق",
    title: "مطور واجهات أمامية متقدم",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    bio: "أحمد توفيق متخصص في تطوير واجهات المستخدم باستخدام تقنيات حديثة مثل React وTypeScript.",
    specialties: ["React", "TypeScript", "CSS"],
    students: 2350,
    courses: 15,
    category: "تطوير الويب",
    rating: 4.9,
  },
  {
    id: 2,
    name: "ليانا محمد",
    title: "مطوّرة تطبيقات موبايل",
    imageUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    bio: "ليانا محمد تمتلك خبرة واسعة في تطوير التطبيقات المحمولة باستخدام Flutter وDart، ولديها شغف بتعليم المبتدئين.",
    specialties: ["Flutter", "Dart", "UI/UX"],
    students: 1870,
    courses: 10,
    category: "تطبيقات الجوال",
    rating: 4.8,
  },
  {
    id: 3,
    name: "نورا عبدالله",
    title: "مطوّرة باك إند متخصصة",
    imageUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    bio: "نورا عبدالله مختصة في بناء تطبيقات باك إند باستخدام Python وDjango وتطوير حلول متكاملة للتطبيقات الحديثة.",
    specialties: ["Python", "Django", "APIs"],
    students: 3120,
    courses: 20,
    category: "تطوير الويب",

    rating: 4.7,
  },
  {
    id: 4,
    name: "خالد السليم",
    title: "خبير ذكاء اصطناعي",
    imageUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    bio: "خالد السليم يعمل في مجال الذكاء الاصطناعي وتعلم الآلة منذ أكثر من 10 سنوات وشارك في العديد من المشاريع العالمية.",
    specialties: ["AI", "Machine Learning", "Deep Learning"],
    students: 4280,
    courses: 30,
    category: "الذكاء الاصطناعي",

    rating: 4.9,
  },
  {
    id: 5,
    name: "لمى القحطاني",
    title: "مصممة تجارب مستخدم معتمدة",
    imageUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    bio: "لمى القحطاني تركز على تقديم حلول تصميم مبتكرة لتحسين تجربة المستخدم باستخدام أدوات مثل Figma وAdobe XD.",
    specialties: ["UX Design", "Figma", "Adobe XD"],
    students: 1650,
    courses: 12,
    category: "التصميم",

    rating: 4.6,
  },
  {
    id: 6,
    name: "تركي الحربي",
    title: "خبير أمن معلومات",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    bio: "تركي الحربي متخصص في الأمن السيبراني وحماية الأنظمة والشبكات من الهجمات الإلكترونية.",
    specialties: ["Cybersecurity", "Network Security", "Penetration Testing"],
    students: 2750,
    courses: 18,
    category: "الأمن السيبراني",

    rating: 4.8,
  },
  {
    id: 7,
    name: "ياسر الغامدي",
    title: "مطوّر Full Stack",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    bio: "ياسر الغامدي خبير في تطوير التطبيقات باستخدام تقنيات مثل Node.js وJavaScript وHTML/CSS.",
    specialties: ["Node.js", "JavaScript", "HTML/CSS"],
    students: 1890,
    courses: 22,
    category: "تطوير الويب",

    rating: 4.5,
  },
  {
    id: 8,
    name: "ندى الرشيد",
    title: "عالمة بيانات",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    bio: "ندى الرشيد تعمل في مجال علم البيانات ولديها خبرة في تحليل البيانات باستخدام Python وأدوات مثل Pandas وMatplotlib.",
    specialties: ["Data Science", "Python", "Pandas"],
    students: 3210,
    courses: 25,
    category: "علم البيانات",

    rating: 4.7,
  },
  {
    id: 9,
    name: "فهد العتيبي",
    title: "مطوّر واجهات أمامية",
    imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    bio: "فهد العتيبي متخصص في تطوير واجهات المستخدم باستخدام Vue.js وJavaScript، ويعشق تحسين الأداء والتفاعل.",
    specialties: ["Vue.js", "JavaScript", "Performance Optimization"],
    students: 1420,
    courses: 8,
    category: "تطوير الويب",

    rating: 4.4,
  },
  {
    id: 10,
    name: "عبدالعزيز السعد",
    title: "مطوّر Angular معتمد",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
    bio: "عبدالعزيز السعد يمتلك خبرة متميزة في استخدام Angular لبناء تطبيقات ويب معقدة ويمتلك شغفاً بالبرمجة.",
    specialties: ["Angular", "TypeScript", "RxJS"],
    students: 2345,
    courses: 10,
    category: "تطوير الويب",

    rating: 4.6,
  },
  {
    id: 11,
    name: "نايف القحطاني",
    title: "مهندس DevOps",
    imageUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    bio: "نايف القحطاني متخصص في DevOps مع خبرة واسعة في أدوات مثل Docker وKubernetes وCI/CD لنشر التطبيقات بشكل أسرع وأكثر أمانًا.",
    specialties: ["DevOps", "Docker", "Kubernetes"],
    students: 1780,
    courses: 14,
    category: "DevOps",

    rating: 4.8,
  },
];

export async function GET() {
  return NextResponse.json(instructors);
}
