import { NextResponse } from "next/server";

const courses = [
  {
    id: 1,
    title: "احتراف React مع TypeScript",
    description: "تطوير تطبيقات ويب متقدمة باستخدام React وTypeScript",
    duration: "15 ساعة",
    price: "349",
    instructor: "أحمد توفيق",
    instructorTitle: "مطور واجهات أمامية متقدم",
    instructorImage: "https://picsum.photos/100/100?person=1",
    level: "متوسط",
    imageUrl: "https://picsum.photos/640/360?react",
    students: 2350,
    rating: 4.9,
    ratingCount: 342,
    category: "تطوير الويب",
    tags: ["React", "TypeScript", "Web Development"],
    featured: true,
    recent: false,
    language: "العربية",
    lastUpdate: "مارس 2025",
    objectives: [
      "بناء تطبيقات React احترافية مع TypeScript",
      "فهم أنماط التصميم المتقدمة في React",
      "استخدام Hooks وContext API بشكل فعال",
      "تطبيق التحقق من النوع باستخدام TypeScript",
      "إنشاء مكونات قابلة لإعادة الاستخدام",
      "تحسين الأداء وتطبيق أفضل الممارسات",
    ],
    requirements: [
      "معرفة أساسية بـ HTML و CSS و JavaScript",
      "فهم أساسي لـ React",
      "حماس للتعلم والتطبيق العملي",
    ],
    sections: [
      {
        id: 1,
        title: "مقدمة في React و TypeScript",
        duration: "3 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وكيفية الاستفادة القصوى",
            duration: "10:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "15:20",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات TypeScript للمطورين",
            duration: "25:30",
            isVideo: true,
            isFree: false,
          },
          {
            id: 104,
            title: "إنشاء أول تطبيق React مع TypeScript",
            duration: "30:45",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "المكونات والحالة في React",
        duration: "4 ساعات",
        lessons: [
          {
            id: 201,
            title: "إنشاء وتنظيم المكونات",
            duration: "22:15",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "استخدام Props مع TypeScript",
            duration: "18:40",
            isVideo: true,
            isFree: false,
          },
          {
            id: 203,
            title: "إدارة الحالة باستخدام Hooks",
            duration: "35:10",
            isVideo: true,
            isFree: false,
          },
          {
            id: 204,
            title: "واجهات TypeScript للحالة والخصائص",
            duration: "28:30",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 3,
        title: "تطبيقات متقدمة",
        duration: "8 ساعات",
        lessons: [
          {
            id: 301,
            title: "بناء نظام المصادقة",
            duration: "45:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 302,
            title: "إدارة الحالة العالمية باستخدام Context API",
            duration: "38:15",
            isVideo: true,
            isFree: false,
          },
          {
            id: 303,
            title: "تحسين الأداء والتحميل المتأخر",
            duration: "32:45",
            isVideo: true,
            isFree: false,
          },
          {
            id: 304,
            title: "تطبيق كامل: منصة المحتوى التعليمي",
            duration: "1:15:30",
            isVideo: true,
            isFree: false,
          },
          {
            id: 305,
            title: "الملحقات والموارد",
            duration: "05:20",
            isVideo: false,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 1,
        user: "محمد العمري",
        userImage: "https://picsum.photos/100/100?person=2",
        userTitle: "مطور ويب",
        rating: 5,
        date: "15 مارس 2025",
        comment:
          "دورة ممتازة جداً، استفدت منها كثيراً في تطوير مهاراتي في React وTypeScript. أسلوب المدرب واضح وسلس وأمثلة عملية مفيدة.",
        helpful: 24,
      },
      {
        id: 2,
        user: "سارة الأحمد",
        userImage: "https://picsum.photos/100/100?person=3",
        userTitle: "مصممة واجهات",
        rating: 4,
        date: "2 مارس 2025",
        comment:
          "دورة قيمة ومفيدة جداً، لكن كنت أتمنى المزيد من التطبيقات العملية. شرح المدرب ممتاز وواضح وخصوصاً الأجزاء المتعلقة بـ TypeScript.",
        helpful: 18,
      },
    ],
  },
  {
    id: 2,
    title: "تعلم Flutter من البداية",
    description: "بناء تطبيقات جوال متعددة المنصات باستخدام Flutter وDart",
    duration: "20 ساعة",
    price: "449",
    instructor: "ليانا محمد",
    instructorTitle: "مطوّرة تطبيقات موبايل",
    instructorImage: "https://picsum.photos/100/100?person=4",
    level: "مبتدئ",
    imageUrl: "https://picsum.photos/640/360?flutter",
    students: 1870,
    rating: 4.8,
    ratingCount: 215,
    category: "تطبيقات الجوال",
    tags: ["Flutter", "Mobile", "Dart"],
    featured: false,
    recent: true,
    language: "العربية",
    lastUpdate: "أبريل 2025",
    objectives: [
      "التعرف على أساسيات لغة Dart",
      "بناء واجهات مستخدم جذابة باستخدام Flutter",
      "تطوير تطبيقات تعمل على أندرويد و iOS من كود واحد",
      "التعامل مع قواعد البيانات وخدمات الويب",
      "نشر التطبيق على متاجر التطبيقات",
    ],
    requirements: [
      "معرفة أساسية بأي لغة برمجة",
      "جهاز حاسوب يمكنه تشغيل Android Studio",
      "حماس للتعلم وتطوير تطبيقات الجوال",
    ],
    sections: [
      {
        id: 1,
        title: "مقدمة في Flutter وDart",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Flutter",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات لغة Dart",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات المستخدم",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم الـ Widgets في Flutter",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تصميم تخطيطات متقدمة",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 1,
        user: "أحمد الشمري",
        userImage: "https://picsum.photos/100/100?person=5",
        userTitle: "مبرمج مبتدئ",
        rating: 5,
        date: "10 أبريل 2025",
        comment:
          "دورة رائعة للمبتدئين! استطعت بناء أول تطبيق خاص بي بسهولة. الشرح واضح وسلس.",
        helpful: 32,
      },
    ],
  },
  {
    id: 3,
    title: "بايثون متقدم مع Django",
    description: "بناء تطبيقات ويب احترافية باستخدام بايثون وإطار عمل Django",
    duration: "18 ساعة",
    price: "399",
    instructor: "نورا عبدالله",
    instructorTitle: "مطوّرة باك إند متخصصة",
    instructorImage: "https://picsum.photos/100/100?person=6",
    level: "متقدم",
    imageUrl: "https://picsum.photos/640/360?python",
    students: 3120,
    rating: 4.7,
    ratingCount: 287,
    category: "تطوير الويب",
    tags: ["Python", "Django", "Backend"],
    featured: true,
    recent: true,
    language: "العربية",
    lastUpdate: "فبراير 2025",
    objectives: [
      "تعميق المعرفة بلغة Python وميزاتها المتقدمة",
      "إتقان أساسيات ومفاهيم إطار عمل Django",
      "بناء نماذج قواعد بيانات فعالة باستخدام Django ORM",
      "تطوير واجهات برمجة تطبيقات (APIs) باستخدام Django REST framework",
      "تأمين تطبيقات الويب وحماية البيانات",
      "نشر تطبيقات Django على خوادم حقيقية",
    ],
    requirements: [
      "معرفة جيدة بأساسيات لغة Python",
      "فهم أساسي لمفاهيم تطوير الويب (HTTP, REST)",
      "الإلمام بقواعد البيانات (SQL أساسي)",
      "الرغبة في تعلم تطوير تطبيقات الويب باستخدام Django",
    ],
    sections: [
      {
        id: 1,
        title: "مقدمة في Django و Python المتقدم",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Django",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير لـ Django",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "ميزات Python المتقدمة للتطوير الخلفي",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء النماذج وقواعد البيانات مع Django ORM",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "تعريف النماذج في Django",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "إدارة قواعد البيانات باستخدام Django Migrations",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 2,
        user: "ليلى محمد",
        userImage: "https://picsum.photos/100/100?person=7",
        userTitle: "مصممة UX/UI",
        rating: 4,
        date: "15 أبريل 2025",
        comment: "الدورة مفيدة جدًا، لكن بعض الأجزاء تحتاج إلى تفصيل أكثر.",
        helpful: 15,
      },
    ],
  },

  {
    id: 4,
    title: "الذكاء الاصطناعي التطبيقي",
    description: "تعلم أساسيات التعلم الآلي ومعالجة البيانات باستخدام Python",
    duration: "25 ساعة",
    price: "599",
    instructor: "خالد السليم",
    instructorTitle: "خبير ذكاء اصطناعي",
    instructorImage: "https://picsum.photos/100/100?person=7",
    level: "متقدم",
    imageUrl: "https://picsum.photos/640/360?ai",
    students: 4280,
    rating: 4.9,
    ratingCount: 415,
    category: "الذكاء الاصطناعي",
    tags: ["AI", "Machine Learning", "Python"],
    featured: true,
    recent: false,
    language: "العربية",
    lastUpdate: "يناير 2025",
    sections: [
      {
        id: 1,
        title: "مقدمة في Flutter وDart",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Flutter",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات لغة Dart",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات المستخدم",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم الـ Widgets في Flutter",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تصميم تخطيطات متقدمة",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 3,
        user: "خالد العبدالله",
        userImage: "https://picsum.photos/100/100?person=9",
        userTitle: "طالب جامعي",
        rating: 5,
        date: "20 أبريل 2025",
        comment: "شرح ممتاز وأسلوب المدرب شيق جدًا. تعلمت الكثير.",
        helpful: 28,
      },
    ],
    objectives: [
      "فهم المبادئ الأساسية للتعلم الآلي.",
      "تطبيق خوارزميات التعلم الآلي المختلفة على مجموعات البيانات.",
      "استخدام مكتبات Python الشائعة في مجال الذكاء الاصطناعي (مثل NumPy, Pandas, Scikit-learn).",
      "معالجة وتنظيف البيانات لتحضيرها للتحليل.",
      "تقييم أداء نماذج التعلم الآلي.",
      "تطبيق مفاهيم الذكاء الاصطناعي في سيناريوهات عملية.",
    ],
    requirements: [
      "معرفة قوية بلغة Python.",
      "فهم أساسي للجبر الخطي والإحصاء.",
      "يفضل وجود خبرة في التعامل مع البيانات.",
      "جهاز كمبيوتر مثبت عليه Python والمكتبات اللازمة.",
    ],
  },
  {
    id: 5,
    title: "تصميم UI/UX احترافي",
    description: "من الصفر إلى الاحتراف في تصميم تجارب المستخدم",
    duration: "12 ساعة",
    price: "299",
    instructor: "لمى القحطاني",
    instructorTitle: "مصممة تجارب مستخدم معتمدة",
    instructorImage: "https://picsum.photos/100/100?person=8",
    level: "مبتدئ",
    imageUrl: "https://picsum.photos/640/360?design",
    students: 1650,
    rating: 4.6,
    ratingCount: 132,
    category: "التصميم",
    tags: ["UI/UX", "Figma", "Adobe XD"],
    featured: false,
    recent: true,
    language: "العربية",
    lastUpdate: "ديسمبر 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في Flutter وDart",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Flutter",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات لغة Dart",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات المستخدم",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم الـ Widgets في Flutter",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تصميم تخطيطات متقدمة",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 4,
        user: "سارة علي",
        userImage: "https://picsum.photos/100/100?person=11",
        userTitle: "مسوقة رقمية",
        rating: 3,
        date: "25 أبريل 2025",
        comment: "توقعت محتوى أكثر تقدمًا، الدورة مناسبة للمبتدئين فقط.",
        helpful: 8,
      },
    ],
    objectives: [
      "فهم مبادئ تصميم تجربة المستخدم (UX).",
      "تطبيق منهجيات البحث في تجربة المستخدم.",
      "إنشاء شخصيات المستخدم وسيناريوهات الاستخدام.",
      "تصميم هياكل معلومات فعالة.",
      "إنشاء نماذج أولية (Wireframes و Prototypes) باستخدام أدوات مثل Figma و Adobe XD.",
      "فهم مبادئ تصميم واجهة المستخدم (UI) الجذابة وسهلة الاستخدام.",
      "تطبيق مبادئ إمكانية الوصول في التصميم.",
    ],
    requirements: [
      "لا يشترط وجود خبرة سابقة في التصميم.",
      "الرغبة في تعلم كيفية تصميم تجارب مستخدم ممتازة.",
      "الإلمام الأساسي باستخدام الكمبيوتر والإنترنت.",
      "يفضل وجود جهاز كمبيوتر مثبت عليه أدوات التصميم (Figma أو Adobe XD - قد يتم توفير نسخة تجريبية).",
    ],
  },
  {
    id: 6,
    title: "الأمن السيبراني الأساسي",
    description: "حماية الأنظمة والشبكات من الهجمات الإلكترونية",
    duration: "10 ساعات",
    price: "499",
    instructor: "تركي الحربي",
    instructorTitle: "خبير أمن معلومات",
    instructorImage: "https://picsum.photos/100/100?person=9",
    level: "متوسط",
    imageUrl: "https://picsum.photos/640/360?security",
    students: 2750,
    rating: 4.8,
    ratingCount: 198,
    category: "الأمن السيبراني",
    tags: ["Security", "Ethical Hacking", "Networking"],
    featured: true,
    recent: false,
    language: "العربية",
    lastUpdate: "نوفمبر 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في Flutter وDart",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Flutter",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات لغة Dart",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات المستخدم",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم الـ Widgets في Flutter",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تصميم تخطيطات متقدمة",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 5,
        user: "يوسف إبراهيم",
        userImage: "https://picsum.photos/100/100?person=16",
        userTitle: "مدير مشروع",
        rating: 5,
        date: "30 أبريل 2025",
        comment: "دورة منظمة ومحتوى ثري. أنصح بها بشدة لكل مهتم.",
        helpful: 45,
      },
    ],
    objectives: [
      "فهم المفاهيم الأساسية للأمن السيبراني.",
      "التعرف على أنواع الهجمات الإلكترونية الشائعة.",
      "تطبيق إجراءات لحماية الأنظمة والبيانات.",
      "فهم أساسيات أمن الشبكات.",
      "التعرف على أدوات الأمن السيبراني الأساسية.",
      "فهم أهمية الوعي الأمني للمستخدمين.",
    ],
    requirements: [
      "الإلمام الأساسي باستخدام الكمبيوتر والإنترنت.",
      "فهم عام لمفاهيم تكنولوجيا المعلومات.",
      "الرغبة في تعلم كيفية حماية الأصول الرقمية.",
      "لا يشترط وجود خبرة تقنية متقدمة.",
    ],
  },
  {
    id: 7,
    title: "تطوير APIs مع Node.js",
    description: "بناء واجهات برمجة تطبيقات احترافية باستخدام Node.js",
    duration: "14 ساعة",
    price: "449",
    instructor: "ياسر الغامدي",
    instructorTitle: "مطوّر Full Stack",
    instructorImage: "https://picsum.photos/100/100?person=10",
    level: "متوسط",
    imageUrl: "https://picsum.photos/640/360?nodejs",
    students: 1890,
    rating: 4.5,
    ratingCount: 156,
    category: "تطوير الويب",
    tags: ["Node.js", "API", "Backend"],
    featured: false,
    recent: true,
    language: "العربية",
    lastUpdate: "أكتوبر 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في تطوير Node.js و APIs",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة في Node.js وأهميته في تطوير الـ APIs",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة تطوير Node.js",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "مفاهيم أساسية في APIs و RESTful APIs",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات برمجة التطبيقات باستخدام Express.js",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مقدمة في Express.js وتثبيته",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تعريف المسارات (Routes) ومعالجة الطلبات",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
          {
            id: 203,
            title: "التعامل مع البيانات (JSON) في الـ APIs",
            duration: "30:00",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 3,
        title: "تأمين واختبار الـ APIs",
        duration: "4 ساعات",
        lessons: [
          {
            id: 301,
            title: "أساسيات تأمين الـ APIs والمصادقة",
            duration: "30:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 302,
            title: "اختبار الـ APIs باستخدام Postman",
            duration: "25:45",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 5,
        user: "يوسف إبراهيم",
        userImage: "https://picsum.photos/100/100?person=16",
        userTitle: "مدير مشروع",
        rating: 5,
        date: "30 أبريل 2025",
        comment: "دورة منظمة ومحتوى ثري. أنصح بها بشدة لكل مهتم.",
        helpful: 45,
      },
    ],
    objectives: [
      "فهم أساسيات بناء واجهات برمجة التطبيقات (APIs).",
      "تعلم كيفية استخدام Node.js و Express.js في بناء APIs.",
      "تصميم وتنفيذ نقاط نهاية (endpoints) مختلفة للـ API.",
      "التعامل مع البيانات بتنسيقات JSON.",
      "تأمين الـ APIs باستخدام آليات المصادقة والترخيص.",
      "اختبار الـ APIs باستخدام أدوات مثل Postman.",
    ],
    requirements: [
      "معرفة أساسية بلغة JavaScript.",
      "فهم مفاهيم تطوير الويب الأساسية (HTTP, REST).",
      "تثبيت Node.js و npm على جهازك.",
    ],
  },
  {
    id: 8,
    title: "علم البيانات مع Python",
    description: "تحليل البيانات وعرضها باستخدام Pandas وMatplotlib",
    duration: "16 ساعة",
    price: "549",
    instructor: "ندى الرشيد",
    instructorTitle: "عالمة بيانات",
    instructorImage: "https://picsum.photos/100/100?person=11",
    level: "متوسط",
    imageUrl: "https://picsum.photos/640/360?data",
    students: 3210,
    rating: 4.7,
    ratingCount: 245,
    category: "علم البيانات",
    tags: ["Data Science", "Python", "Pandas"],
    featured: true,
    recent: false,
    language: "العربية",
    lastUpdate: "سبتمبر 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في علم البيانات و Python",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة في علم البيانات وأهميته",
            duration: "15:00",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "أساسيات لغة Python لعلم البيانات",
            duration: "45:00",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "إعداد بيئة العمل لأدوات علم البيانات",
            duration: "20:00",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "تحليل البيانات باستخدام Pandas",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مقدمة في مكتبة Pandas وهياكل البيانات",
            duration: "30:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تنظيف البيانات ومعالجتها باستخدام Pandas",
            duration: "50:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 203,
            title: "تحليل البيانات واستخلاص المعلومات",
            duration: "40:00",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 3,
        title: "تصور البيانات باستخدام Matplotlib",
        duration: "6 ساعات",
        lessons: [
          {
            id: 301,
            title: "مقدمة في مكتبة Matplotlib وأنواع الرسوم البيانية",
            duration: "35:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 302,
            title: "إنشاء رسوم بيانية احترافية لتصور البيانات",
            duration: "45:00",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 6,
        user: "نورة السالم",
        userImage: "https://picsum.photos/100/100?person=18",
        userTitle: "محللة بيانات",
        rating: 4,
        date: "5 مايو 2025",
        comment: "التطبيق العملي كان قليلًا، لكن المفاهيم الأساسية واضحة.",
        helpful: 12,
      },
    ],
    objectives: [
      "تعلم أساسيات لغة Python المستخدمة في علم البيانات.",
      "استخدام مكتبة Pandas لتحليل ومعالجة البيانات.",
      "تنظيف البيانات وتحويلها لتناسب التحليل.",
      "إجراء تحليلات استكشافية للبيانات (EDA).",
      "تصور البيانات باستخدام مكتبة Matplotlib.",
      "فهم أنواع مختلفة من الرسوم البيانية واستخداماتها.",
    ],
    requirements: [
      "معرفة أساسية بلغة Python.",
      "فهم مبادئ علم الإحصاء الأساسية (اختياري ولكن مفيد).",
      "تثبيت Python وبيئة تطوير مناسبة (مثل Anaconda).",
    ],
  },
  {
    id: 9,
    title: "تطوير تطبيقات مع Vue.js",
    description: "بناء تطبيقات ويب تفاعلية باستخدام Vue.js",
    duration: "12 ساعة",
    price: "379",
    instructor: "فهد العتيبي",
    instructorTitle: "مطوّر واجهات أمامية",
    instructorImage: "https://picsum.photos/100/100?person=12",
    level: "مبتدئ",
    imageUrl: "https://picsum.photos/640/360?vue",
    students: 1420,
    rating: 4.4,
    ratingCount: 98,
    category: "تطوير الويب",
    tags: ["Vue.js", "Frontend", "JavaScript"],
    featured: false,
    recent: true,
    language: "العربية",
    lastUpdate: "أغسطس 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في Vue.js",
        duration: "3 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة في Vue.js ومميزاته",
            duration: "15:00",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة تطوير Vue.js",
            duration: "25:00",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات Vue Instance",
            duration: "30:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 104,
            title: "ربط البيانات (Data Binding) في Vue.js",
            duration: "20:00",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "المكونات (Components) والتوجيهات (Directives)",
        duration: "5 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم المكونات وأهميتها في Vue.js",
            duration: "30:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "إنشاء واستخدام المكونات",
            duration: "40:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 203,
            title: "نظرة على التوجيهات الأساسية (v-if, v-for, v-bind, v-on)",
            duration: "45:00",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 3,
        title: "إدارة الحالة والتوجيه (مقدمة)",
        duration: "4 ساعات",
        lessons: [
          {
            id: 301,
            title: "مقدمة في إدارة الحالة مع Vuex (مفاهيم أساسية)",
            duration: "35:00",
            isVideo: true,
            isFree: false,
          },
          {
            id: 302,
            title: "مقدمة في توجيه الصفحات باستخدام Vue Router (مفاهيم أساسية)",
            duration: "40:00",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 7,
        user: "عمر حسين",
        userImage: "https://picsum.photos/100/100?person=20",
        userTitle: "مهندس برمجيات",
        rating: 5,
        date: "10 مايو 2025",
        comment: "دورة متكاملة تغطي جميع الجوانب المهمة. المدرب متمكن.",
        helpful: 51,
      },
    ],
    objectives: [
      "فهم أساسيات إطار عمل Vue.js.",
      "تعلم كيفية إنشاء مكونات (components) Vue.js.",
      "التعامل مع توجيهات Vue.js (directives) مثل v-if و v-for.",
      "إدارة حالة التطبيق باستخدام Vuex (مقدمة).",
      "التعامل مع الأحداث (events) وإدخالات المستخدم.",
      "توجيه (routing) الصفحات في تطبيقات Vue.js باستخدام Vue Router (مقدمة).",
    ],
    requirements: [
      "معرفة أساسية بلغات HTML و CSS و JavaScript.",
      "فهم مفاهيم تطوير الويب الأساسية.",
      "لا يلزم وجود خبرة سابقة مع أطر عمل JavaScript.",
    ],
  },
  {
    id: 10,
    title: "Angular للمحترفين",
    description: "تطوير تطبيقات ويب معقدة باستخدام Angular",
    duration: "20 ساعة",
    price: "499",
    instructor: "عبدالعزيز السعد",
    instructorTitle: "مطوّر Angular معتمد",
    instructorImage: "https://picsum.photos/100/100?person=13",
    level: "متقدم",
    imageUrl: "https://picsum.photos/640/360?angular",
    students: 2345,
    rating: 4.6,
    ratingCount: 187,
    category: "تطوير الويب",
    tags: ["Angular", "TypeScript", "Frontend"],
    featured: true,
    recent: false,
    language: "العربية",
    lastUpdate: "يوليو 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في Flutter وDart",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Flutter",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات لغة Dart",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات المستخدم",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم الـ Widgets في Flutter",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تصميم تخطيطات متقدمة",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 9,
        user: "عبدالله ناصر",
        userImage: "https://picsum.photos/100/100?person=24",
        userTitle: "مصمم جرافيك",
        rating: 4,
        date: "20 مايو 2025",
        comment: "الدورة ساعدتني في فهم الأساسيات، وأتطلع إلى دورات متقدمة.",
        helpful: 18,
      },
    ],
    objectives: [
      "فهم أساسيات إطار عمل Angular.",
      "إنشاء تطبيقات معقدة باستخدام Angular.",
      "تعلم كيفية استخدام TypeScript في تطوير Angular.",
      "إدارة الحالة باستخدام RxJS.",
      "تطبيق نمط التصميم MVC في Angular.",
      "التعامل مع خدمات HTTP وRESTful APIs.",
    ],
    requirements: [
      "معرفة أساسية بلغة JavaScript و TypeScript.",
      "فهم مفاهيم تطوير الويب الأساسية.",
      "يفضل وجود خبرة سابقة مع Angular أو أطر عمل مشابهة.",
    ],
  },

  {
    id: 11,
    title: "DevOps الأساسيات",
    description: "إدارة البنية التحتية ونشر التطبيقات باستخدام أدوات DevOps",
    duration: "22 ساعة",
    price: "649",
    instructor: "نايف القحطاني",
    instructorTitle: "مهندس DevOps",
    instructorImage: "https://picsum.photos/100/100?person=14",
    level: "متوسط",
    imageUrl: "https://picsum.photos/640/360?devops",
    students: 1780,
    rating: 4.8,
    ratingCount: 210,
    category: "DevOps",
    tags: ["Docker", "Kubernetes", "CI/CD"],
    featured: true,
    recent: true,
    language: "العربية",
    lastUpdate: "يونيو 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في Flutter وDart",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Flutter",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات لغة Dart",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات المستخدم",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم الـ Widgets في Flutter",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تصميم تخطيطات متقدمة",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 1,
        user: "أحمد الشمري",
        userImage: "https://picsum.photos/100/100?person=5",
        userTitle: "مبرمج مبتدئ",
        rating: 5,
        date: "10 أبريل 2025",
        comment:
          "دورة رائعة للمبتدئين! استطعت بناء أول تطبيق خاص بي بسهولة. الشرح واضح وسلس.",
        helpful: 32,
      },
    ],
  },
  {
    id: 12,
    title: "Laravel من الصفر",
    description: "بناء تطبيقات ويب متكاملة باستخدام إطار عمل Laravel",
    duration: "17 ساعة",
    price: "429",
    instructor: "منى الحمود",
    instructorTitle: "مطوّرة PHP متخصصة",
    instructorImage: "https://picsum.photos/100/100?person=15",
    level: "مبتدئ",
    imageUrl: "https://picsum.photos/640/360?laravel",
    students: 2950,
    rating: 4.7,
    ratingCount: 265,
    category: "تطوير الويب",
    tags: ["Laravel", "PHP", "Backend"],
    featured: false,
    recent: true,
    language: "العربية",
    lastUpdate: "مايو 2024",
    sections: [
      {
        id: 1,
        title: "مقدمة في Flutter وDart",
        duration: "4 ساعات",
        lessons: [
          {
            id: 101,
            title: "مقدمة الدورة وأهمية Flutter",
            duration: "12:30",
            isVideo: true,
            isFree: true,
          },
          {
            id: 102,
            title: "إعداد بيئة التطوير",
            duration: "20:15",
            isVideo: true,
            isFree: true,
          },
          {
            id: 103,
            title: "أساسيات لغة Dart",
            duration: "35:40",
            isVideo: true,
            isFree: false,
          },
        ],
      },
      {
        id: 2,
        title: "بناء واجهات المستخدم",
        duration: "6 ساعات",
        lessons: [
          {
            id: 201,
            title: "مفهوم الـ Widgets في Flutter",
            duration: "25:20",
            isVideo: true,
            isFree: false,
          },
          {
            id: 202,
            title: "تصميم تخطيطات متقدمة",
            duration: "40:15",
            isVideo: true,
            isFree: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: 11,
        user: "جاسم محمد",
        userImage: "https://picsum.photos/100/100?person=28",
        userTitle: "مختص أمن سيبراني",
        rating: 2,
        date: "30 مايو 2025",
        comment: "الدورة لم تتطرق إلى المواضيع المتقدمة التي كنت أبحث عنها.",
        helpful: 3,
      },
    ],
  },
];

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  const { id } = params;

  if (id) {
    const courseId = parseInt(id);
    const course = courses.find((c) => c.id === courseId);

    if (!course) {
      return NextResponse.json({ error: "Course not found" }, { status: 404 });
    }

    return NextResponse.json(course);
  }
}
